### ISSUE TITLE
Scaling issue #2

### ISSUE THREAD

**Issue by Hangman** [crashinvaders/gdx-texture-packer-gui#42]
I think there's a system scaling adoption working in the background (lwjgl or scene2D or libgdx viewport) which kind of makes it worse in this case :D

3840*2160, 200% system scaling, 200% texture packer scaling
![1](https://user-images.githubusercontent.com/108926/40145252-6981c154-5961-11e8-8e0b-1b76033d99e7.png)

3840*2160, 150% system scaling, 200% texture packer scaling
![2](https://user-images.githubusercontent.com/108926/40145276-812917f8-5961-11e8-9ab0-09f661ea4824.png)

As you can see, the "viewport" the UI uses is messed up. It depends on the system scaling somehow. Most of the UI is visible when i maximize the window.

3840*2160, 200% system scaling, 200% texture packer scaling
![3](https://user-images.githubusercontent.com/108926/40145572-b6af2f60-5962-11e8-822c-2b11d23f341c.png)

And if you're wondering what happens with 100% system scaling, here you go:
3840*2160, 100% system scaling, 200% texture packer scaling
![4](https://user-images.githubusercontent.com/108926/40145865-bfadff00-5963-11e8-9d92-0681b0c79102.png)

**Comment by metaphore** [comment]
The link is broken, could you please update it.

**Comment by Hangman** [comment]
Done. Sorry i messed up the link syntax :~(

**Comment by metaphore** [comment]
Yep, looks like something related to the issue. I will update to a new stable LibGDX release once it's out and let you know, till then let's keep it open.

**Comment by Hangman** [comment]
LibGDX 1.9.9 is released, they just forgot to announce it on the official website.

**Comment by metaphore** [comment]
@Hangman thanks for reminding me, completely forgot about it. I still have issues reproducing it, so I guess you should try it and see if the update helps.

[gdx-texturepacker-4.8.2.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/2672371/gdx-texturepacker-4.8.2.zip)

**Comment by Hangman** [comment]
It's fixed!!! Hooray. Thanks for updating!

**Comment by metaphore** [comment]
Alright, cool! I will roll out public release soon.
